version: '3.8'

services:
  shared-state:
    build:
      context: ./remote_repos/mf-app-store
      dockerfile: Dockerfile
    volumes:
      - ./remote_repos/mf-app-store:/app
    ports:
      - "4000:4000"
    command: ["npm", "run", "serve"]

  remote:
    build:
      context: ./remote_repos/mf-app-react-remote
      dockerfile: Dockerfile
    volumes:
      - ./remote_repos/mf-app-react-remote:/app
    ports:
      - "5001:5001"
    depends_on:
      - shared-state
    command: ["npm", "run", "serve"]


